language: python
matrix:
  include:
    - os: linux
      dist: xenial
      python: "nightly"
    - os: linux
      dist: xenial
      python: "3.9-dev"
    - os: linux
      dist: xenial
      python: "3.8"
    - os: linux
      dist: xenial
      python: "3.7"
    - os: linux
      dist: trusty
      python: "3.6"
    - os: linux
      dist: trusty
      python: "3.5"
    - os: linux
      dist: trusty
      python: "3.4"
    - os: linux
      dist: trusty
      python: "2.7"
    - os: linux
      dist: trusty
      python: "pypy3.5"
  allow_failures:
    - python: nightly
    - python: 3.9-dev
    - python: "2.7"
    - python: "3.6"
    - python: "3.4"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest test/
after_success:
  - pytest --cov=fishbase test/
  - coveralls